platform:
  - x64

environment:
  MSYSTEM: MINGW64
  CTEST_OUTPUT_ON_FAILURE: 1

cache:
  - C:\msys64\var\cache
  - C:\msys64\mingw64\var\cache

before_build:
  - git submodule update --init --recursive
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syyuu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm --needed -S make mingw-w64-x86_64-{cmake,toolchain,clang,gtkmm3,gtksourceviewmm3,boost,aspell,aspell-en,libgit2,universal-ctags-git,libffi}"

build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER && mkdir build && cd build && cmake -G\"MSYS Makefiles\" -DCMAKE_INSTALL_PREFIX=/mingw64 -DBUILD_TESTING=1 .. && make -j$(nproc) && make test"
